version: '3.8'
services:
    server:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        networks:
            - app-network
        volumes:
            - ./:/var/www
            - ./nginx.conf.d:/etc/nginx/conf.d/
networks:
    app-network:
        driver: bridge
